import { useMemo, useState } from "react";
import { ArrowRight, Bot, CalendarCheck, Check, ChevronDown, Clock3, Database, Globe2, HeartPulse, MessageSquare, PhoneCall, Play, ShieldCheck, Sparkles, Star, Target, Users, Zap } from "lucide-react";

const specialties = ["Dental & Implant Clinics", "Aesthetic Clinics", "Psychiatry & Mental Health", "Private Medical Clinics", "Physical Therapy", "Specialty Practices"];
const faqs = [
  ["Does ZAAD replace our reception team?", "No. ZAAD handles repetitive first-response, qualification and follow-up workflows while your team stays in control of conversations and appointments."],
  ["Can patients book directly?", "Yes. ZAAD can guide qualified enquiries toward the appropriate booking path and keep the conversation moving until the next step is completed."],
  ["Can ZAAD recover missed calls?", "Yes. A missed call sends an automatic text within a minute with a link to a short booking form. The patient enters their name, reason for visit and preferred time, then books."],
  ["Can we use our existing systems?", "ZAAD is designed around your existing patient journey. Integrations should be scoped around the tools your practice already relies on rather than forcing a complete replacement."],
  ["Is patient data secure?", "Security and access controls should be configured around your actual deployment and jurisdiction. We do not claim a healthcare certification unless the implementation has it."],
  ["How quickly can we launch?", "The launch path depends on your current website, calendars, communication channels and practice systems. A strategy call is used to map the implementation before promising a timeline."],
];

function SectionTitle({ eyebrow, title, accent, text }: { eyebrow: string; title: string; accent: string; text: string }) {
  return <div className="z-section-title"><span className="z-kicker">{eyebrow}</span><h2>{title} <em>{accent}</em></h2><p>{text}</p></div>;
}

export default function ZaadV2() {
  const [faq, setFaq] = useState<number | null>(null);
  const [calc, setCalc] = useState({ leads: 100, rate: 20, value: 1500 });
  const [demo, setDemo] = useState(0);
  const booked = Math.round(calc.leads * calc.rate / 100);
  const potential = Math.round(calc.leads * Math.min(calc.rate + 10, 90) / 100);
  const extra = Math.max(potential - booked, 0);
  const recovery = extra * calc.value;
  const demoSteps = useMemo(() => [
    ["GOOGLE / META", "Patient discovers the practice", Globe2],
    ["NEW ENQUIRY", "Form, chat or call is captured", MessageSquare],
    ["ZAAD AGENT", "Immediate response + qualification", Bot],
    ["BOOKING", "Qualified patient moves forward", CalendarCheck],
    ["GROWTH LOOP", "Review + reactivation keeps the relationship moving", RefreshIcon],
  ] as const, []);
  const DemoIcon = demoSteps[demo]?.[2] ?? Bot;

  return <main className="zaad-v2">
    <header className="z-nav"><a className="z-logo" href="#top">ZAAD<span>.</span></a><nav><a href="#system">System</a><a href="#who">Who it's for</a><a href="#demo">How it works</a><a href="#proof">Proof</a><a href="#faq">FAQ</a></nav><a className="z-nav-cta" href="#contact">BOOK A STRATEGY CALL <ArrowRight size={15}/></a></header>

    <section id="top" className="z-hero">
      <div className="z-grid"/><div className="z-glow z-g1"/><div className="z-glow z-g2"/>
      <div className="z-container z-hero-grid">
        <div>
          <div className="z-eyebrow"><span/> PATIENT ACQUISITION SYSTEM FOR HEALTHCARE</div>
          <h1>MORE PATIENTS.<br/><strong>LESS CHAOS.</strong></h1>
          <p className="z-hero-lead">ZAAD connects acquisition, instant follow-up, booking, missed-call recovery, reputation and reactivation into one patient growth system.</p>
          <div className="z-actions"><a className="z-btn z-primary" href="#contact">BUILD MY PATIENT FLOW <ArrowRight size={17}/></a><a className="z-btn z-outline" href="#demo"><Play size={14} fill="currentColor"/> SEE HOW IT WORKS</a></div>
          <div className="z-trust-row"><span><Check/> Capture enquiries</span><span><Check/> Respond faster</span><span><Check/> Book more patients</span></div>
        </div>
        <div className="z-command-hero"><div className="z-window-head"><span>ZAAD / PATIENT FLOW</span><i>● LIVE SYSTEM</i></div><div className="z-flow"><div className="z-flow-line"/>{[["01","ATTRACT"],["02","CAPTURE"],["03","FOLLOW UP"],["04","BOOK"],["05","PATIENT"]].map(([n,t],i)=><div className="z-flow-node" key={n} style={{animationDelay:`${i*.15}s`}}><b>{n}</b><strong>{t}</strong></div>)}</div><div className="z-hero-stats"><div><small>ENQUIRIES</small><b>128</b><em>example</em></div><div><small>BOOKED</small><b>64</b><em>example</em></div><div><small>RECOVERED</small><b>19</b><em>example</em></div></div><div className="z-float z-float-one"><MessageSquare size={15}/><span><small>ZAAD AGENT</small><b>Appointment confirmed</b></span><Check size={15}/></div><div className="z-float z-float-two"><Star size={14} fill="currentColor"/><span><b>New 5-star review</b><small>“Really easy to book.”</small></span></div></div>
      </div>
    </section>

    <section className="z-proof-strip" id="proof"><div className="z-container"><span>BUILT AROUND WHAT ACTUALLY MATTERS</span><b>PATIENT OPPORTUNITIES</b><b>BOOKED APPOINTMENTS</b><b>SHOW-UPS</b><b>REACTIVATED PATIENTS</b></div></section>

    <section id="system" className="z-light z-pad"><div className="z-container"><SectionTitle eyebrow="01 / THE ENGINE" title="ONE SYSTEM." accent="EVERY HANDOFF." text="Instead of treating ads, leads, calls, appointments and retention as separate problems, ZAAD connects the entire patient journey."/><div className="z-system-grid">{[[Target,"ATTRACT", "Paid search, social, local visibility and focused offers bring the right attention in."],[MessageSquare,"CAPTURE", "Landing pages, forms, chat and calls turn attention into identifiable enquiries."],[Bot,"NURTURE", "Immediate responses and structured follow-up keep qualified patients moving."],[CalendarCheck,"BOOK", "The journey points toward the right appointment and reduces friction."],[PhoneCall,"RECOVER", "Missed calls and stalled conversations get a second chance."],[RefreshIcon,"REACTIVATE", "Past patients and old enquiries become a source of new opportunities."]].map(([Icon,title,text],i)=>{const I=Icon as typeof Target; return <div className="z-card" key={title as string}><span className="z-card-num">0{i+1}</span><I/><h3>{title as string}</h3><p>{text as string}</p><span className="z-card-link">EXPLORE MODULE <ArrowRight size={13}/></span></div>})}</div></div></section>

    <section className="z-dark z-pad"><div className="z-container z-problem"><div><span className="z-kicker">02 / THE REAL PROBLEM</span><h2>YOU MAY NOT HAVE A <em>LEAD PROBLEM.</em></h2><p>Clinics can lose growth between the click and the calendar: weak offers, slow replies, missed calls, inconsistent follow-up, no-shows and dormant databases.</p><a className="z-text-link" href="#demo">SEE THE FULL FLOW <ArrowRight size={15}/></a></div><div className="z-problem-list">{["Not enough consistent enquiries","Leads aren't followed up fast enough","Missed calls become missed appointments","Booked patients don't always show","Great patient experiences never become reviews","Old enquiries sit untouched in the database"].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b><i>×</i></div>)}</div></div></section>

    <section id="demo" className="z-light z-pad"><div className="z-container"><SectionTitle eyebrow="03 / HOW ZAAD WORKS" title="FROM FIRST CLICK" accent="TO PATIENT." text="A simple operating system for the moments that determine whether an enquiry becomes a patient."/><div className="z-demo-grid"><div className="z-demo-tabs">{demoSteps.map(([title,text],i)=><button key={title} className={demo===i?"active":""} onClick={()=>setDemo(i)}><span>0{i+1}</span><b>{title}</b><small>{text}</small><ArrowRight size={15}/></button>)}</div><div className="z-demo-screen"><div className="z-demo-screen-head"><span>LIVE WORKFLOW PREVIEW</span><i>STEP 0{demo+1}</i></div><div className="z-demo-icon"><DemoIcon size={34}/></div><h3>{demoSteps[demo]?.[0]}</h3><p>{demoSteps[demo]?.[1]}</p><div className="z-demo-message">{demo===2 ? <><small>ZAAD AGENT</small><b>“Sorry we missed your call. Book a time that suits you here:”</b><span>Patient: “I'd like to book an appointment.”</span></> : <><small>NEXT ACTION</small><b>{demo===0?"Send qualified traffic to the right offer":demo===1?"Capture intent and contact details":demo===3?"Move the qualified patient into the calendar":"Continue the relationship after the appointment"}</b></>}</div><div className="z-progress"><i style={{width:`${((demo+1)/demoSteps.length)*100}%`}}/></div></div></div></div></section>

    <section id="who" className="z-dark z-pad"><div className="z-container"><SectionTitle eyebrow="04 / WHO IT'S FOR" title="BUILT FOR" accent="PRACTICES." text="The system can be adapted to different private healthcare journeys. The message, qualification and booking logic should match the specialty."/><div className="z-specialties">{specialties.map((s,i)=><div key={s}><span>0{i+1}</span><h3>{s}</h3><p>{i===0?"Consultations, implants, high-intent treatment enquiries and recall workflows.":i===1?"Lead capture, consultation booking, follow-up and reputation workflows.":i===2?"Structured enquiry handling with careful, human-led escalation and booking paths.":i===3?"Service-specific acquisition, qualification and appointment journeys.":i===4?"Enquiry response, qualification, scheduling and reactivation around treatment plans.":"Custom patient journeys around the services, location and economics of the practice."}</p><ArrowRight size={16}/></div>)}</div></div></section>

    <section className="z-light z-pad"><div className="z-container z-split"><div><SectionTitle eyebrow="05 / NEVER LET THE CALL DIE" title="MISSED CALL" accent="RECOVERY." text="When the front desk is busy, the opportunity should not disappear. ZAAD can send an automatic text within a minute with a link to a short booking form."/><div className="z-checks"><span><Check/> Immediate response</span><span><Check/> Conversation continues</span><span><Check/> Patient books through the link</span></div></div><div className="z-phone"><div className="z-phone-top"><PhoneCall size={15}/><b>ZAAD AGENT</b><small>● online</small></div><div className="z-call"><PhoneCall/><span><small>MISSED CALL</small><b>Unknown patient</b></span><em>10:42 AM</em></div><div className="z-bubble agent">Sorry we missed your call. Book a time that suits you here:</div><div className="z-bubble agent"><span className="booking-link-chip">Book your visit →</span></div><div className="z-bubble patient">Name: James Carter · Reason: Check-up · Preferred time: Monday 9:00 AM</div><div className="z-booked"><CalendarCheck/><span><small>APPOINTMENT CONFIRMED</small><b>Monday · 9:00 AM</b></span><Check/></div></div></div></section>

    <section className="z-dark z-pad"><div className="z-container z-split z-reverse"><div className="z-reputation"><div className="z-rep-head"><span>REPUTATION ENGINE</span><Star size={24} fill="currentColor"/></div><div className="z-rep-flow"><div><CalendarCheck/><b>COMPLETED</b></div><ArrowRight/><div><MessageSquare/><b>REQUEST</b></div><ArrowRight/><div className="z-rating"><strong>5.0</strong><span>★★★★★</span><small>Google Review</small></div></div><blockquote>“The team made everything incredibly easy.”<small>— illustrative example</small></blockquote></div><div><SectionTitle eyebrow="06 / REPUTATION" title="GREAT EXPERIENCES" accent="SHOULD SHOW." text="Turn the right moments after an appointment into a thoughtful review request. Build trust without making your team remember every follow-up manually."/></div></div></section>

    <section className="z-light z-pad"><div className="z-container z-split"><div><SectionTitle eyebrow="07 / REACTIVATION" title="YOUR DATABASE" accent="ISN'T DEAD REVENUE." text="Past patients and old enquiries can become a targeted campaign audience instead of a forgotten spreadsheet."/><a className="z-btn z-primary" href="#contact">PLAN A REACTIVATION CAMPAIGN <ArrowRight size={16}/></a></div><div className="z-database"><div className="z-db-head"><Database size={16}/> PATIENT DATABASE <span>1,842 EXAMPLE RECORDS</span></div>{["Alex Stone · inactive 8 months","Maya Jones · past patient 5 months","Ryan Khan · previous enquiry"].map((x,i)=><div className="z-db-row" key={x}><span>{x.slice(0,2).toUpperCase()}</span><b>{x}</b><em>SELECTED</em></div>)}<div className="z-campaign"><small>TARGETED OFFER</small><h3>20% OFF YOUR NEXT APPOINTMENT</h3><p>Example campaign → messaging → replies → rebooking.</p><div><b>84</b><span>REPLIES</span><ArrowRight/><b>31</b><span>REBOOKED</span></div></div></div></div></section>

    <section className="z-dark z-pad"><div className="z-container"><SectionTitle eyebrow="08 / YOUR EXISTING STACK" title="WORK WITH" accent="YOUR SYSTEMS." text="ZAAD should fit the practice rather than force a disruptive replacement. Connect the channels and tools that already power your patient journey."/><div className="z-integrations">{[[Globe2,"Website / Landing Pages"],[Target,"Google & Meta"],[MessageSquare,"SMS / Messaging"],[PhoneCall,"Phone"],[CalendarCheck,"Calendar / Booking"],[Database,"CRM / Practice Systems"]].map(([I,t])=>{const Icon=I as typeof Globe2;return <div key={t as string}><Icon/><b>{t as string}</b><small>CONNECT / CONFIGURE</small></div>})}</div><div className="z-security"><ShieldCheck/><div><b>Healthcare-first deployment mindset</b><p>Access, data handling and integrations should be configured to your actual jurisdiction and stack. Security claims belong to the implementation—not the marketing copy.</p></div></div></div></section>

    <section className="z-light z-pad"><div className="z-container"><SectionTitle eyebrow="09 / OPPORTUNITY MODEL" title="SEE THE" accent="UPSIDE." text="Use this as an illustrative planning model—not a promise. Change the inputs to see how conversion improvements can affect potential booked-patient value."/><div className="z-calculator"><div className="z-sliders">{[["MONTHLY ENQUIRIES","leads",20,500],["CURRENT BOOKING RATE %","rate",5,80],["AVERAGE PATIENT VALUE $","value",100,10000]].map(([label,key,min,max])=>{const k=key as keyof typeof calc;return <label key={key as string}><span>{label as string}<b>{calc[k].toLocaleString()}</b></span><input type="range" min={min as number} max={max as number} value={calc[k]} onChange={e=>setCalc({...calc,[k]:Number(e.target.value)})}/></label>})}</div><div className="z-calc-result"><small>ILLUSTRATIVE ADDITIONAL VALUE</small><strong>${recovery.toLocaleString()}</strong><p>Potentially <b>+{extra}</b> additional booked patients/month if booking rate improves by 10 percentage points.</p><div><span>Current booked <b>{booked}</b></span><span>Illustrative potential <b>{potential}</b></span></div></div></div></div></section>

    <section className="z-dark z-pad"><div className="z-container z-why"><div><SectionTitle eyebrow="10 / WHY THE MODEL WORKS" title="FOCUS ON THE" accent="WHOLE JOURNEY." text="The acquisition channel is only one part of growth. ZAAD is designed around the handoffs where opportunities commonly disappear."/></div><div className="z-why-list">{[[Zap,"Speed = revenue","Respond while intent is high."],[Target,"Better qualification","Send the right patients to the right next step."],[HeartPulse,"Show-ups matter","A booked appointment is not the finish line."],[RefreshIcon,"Compounding growth","Reviews and reactivation create future opportunities."]].map(([I,t,p])=>{const Icon=I as typeof Zap;return <div key={t as string}><Icon/><div><b>{t as string}</b><p>{p as string}</p></div></div>})}</div></div></section>

    <section id="faq" className="z-light z-pad"><div className="z-container z-faq"><SectionTitle eyebrow="11 / QUESTIONS" title="BEFORE YOU" accent="BOOK." text="The practical questions a clinic owner should be able to answer before starting."/><div>{faqs.map(([q,a],i)=><button key={q} className="z-faq-row" onClick={()=>setFaq(faq===i?null:i)}><span><b>0{i+1}</b>{q}</span><ChevronDown className={faq===i?"open":""}/>{faq===i&&<p>{a}</p>}</button>)}</div></div></section>

    <section id="contact" className="z-final"><div className="z-grid"/><div className="z-container"><span className="z-kicker">12 / READY?</span><h2>BUILD A PATIENT FLOW<br/><em>THAT DOESN'T DROP.</em></h2><p>Tell us where your practice is losing opportunities. We'll map the acquisition, follow-up and booking journey around your current setup.</p><div className="z-actions"><a className="z-btn z-primary" href="mailto:hello@zaad.health">BOOK A STRATEGY CALL <ArrowRight size={17}/></a><a className="z-btn z-outline" href="#top">BACK TO TOP <ChevronDown size={15}/></a></div></div></section>
    <footer className="z-footer"><div className="z-container"><a className="z-logo" href="#top">ZAAD<span>.</span></a><span>Patient acquisition systems for healthcare practices.</span><small>© 2026 ZAAD · Illustrative UI numbers are examples.</small></div></footer>
  </main>;
}

function RefreshIcon(props: { size?: number }) { return <RefreshIconSvg {...props}/> }
function RefreshIconSvg({ size=24 }: { size?: number }) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15.5-6.3L21 8"/><path d="M21 3v5h-5"/><path d="M21 12a9 9 0 0 1-15.5 6.3L3 16"/><path d="M3 21v-5h5"/></svg> }
